### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by beevabeeva** [beevabeeva/cgv_game#1]
# MY  T O D O 's
- [ ] Implement this sun thing shader https://threejs.org/examples/?q=sky#webgl_shaders_sky
- [ ] Make normal buildings that can load, for level 0
- [ ] Make Trench (modular, procedural loading or something like that
- [ ] Shooting
- [ ] Sound 
- [ ] powerups + collectibles
- [ ] skybox
- [ ] tiefighter
